import Vue from "vue";
import customCard from './customCard';
import toolbar from './toolbar';
import drawer from './drawer';
import snackbar from './snackbar';
import overlay from './overlay';
Vue.component('customCard', customCard);
Vue.component('toolbar', toolbar);
Vue.component('drawer', drawer);
Vue.component('snackbar', snackbar);
Vue.component('overlay', overlay);